on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            contents/conferences/**.json

      - name: Request for validation
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            echo ""
            
            RESPONSE=$(curl -XPOST -H "Authorization: Bearer ${{ secrets.TOKEN }}" -H "Content-Type: application/json" -d "@$file" -w "\n%{response_code}" https://cc-api.god-oda.workers.dev/api/conferences/validation)
            STATUS=$(echo "${RESPONSE}" | tail -n 1)
            BODY=$(echo "${RESPONSE}" | sed "$ d")
            
            echo "Response body"  
            echo $BODY | jq
            echo ""
          
            echo "Http status code"
            echo $STATUS
            echo ""
          
            if test $STATUS -ne 200; then
              exit 1
            fi
          done