on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'conference-add')
    steps:
      - uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            contents/conferences/**.json

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed\n"
            curl -XPOST -H "Authorization: Bearer ${{ secrets.TOKEN }}" -H "Content-Type: application/json" -d "@$file" https://cc-api.god-oda.workers.dev/api/conferences/validation
          done